### ISSUE TITLE
Video Processing is slow? Why? 

### ISSUE THREAD

**Issue by mustafamerttunali** [galenballew/SDC-Lane-and-Vehicle-Detection-Tracking#1]
Im trying to use  pycuda with this but it is still slow. Why? How can I make this video fast?

Example:

```
def function1
def function2
def function3
def function4

def process_image(frame)

while(ret):
    ret, frame = cap.read()
    ##result =warp_pipeline(frame)

    result = process_image(frame)
    cv2.imshow('sss', result)
    



    if cv2.waitKey(33) & 0xFF == ord('q'):
        break


  
   
    
  

cap.release()
cv2.destroyAllWindows()

```

**Comment by galenballew** [comment]
I am not sure which part of the project you are referring to. Also this project does not use pycuda.

**Comment by mustafamerttunali** [comment]
Im trying to learn lane detection system. I have a Jetson TK1. This project doesnt use pycuda I know, I added pycuda  to use GPU. Im reffering to this project sir. What do you thing? What could be wrong?

**Comment by galenballew** [comment]
That is awesome! The Jetson TX1 should handle this no problem.

Can you please be more specific about which part of the project you are
looking at? There are 3 separate projects within this repository.

Also, feel free to post your actual code. Is the processing slow or is the
video itself slow? Have you tried rendering to a video file and then
watching the video?

**Comment by mustafamerttunali** [comment]
"Part II - Adv Lane Detection and Road Features" sir. I havent tried the rendering to a video file. I'will. I have changed the codes so its diffrent from the separate projects. I have a jetson tx1 too but 2 fps more. :/ 


Edit: I cant render the video. :/ Problem is the: 

File "gpu.py", line 595, in <module>
    ```
clip1 = VideoFileClip("/home/ubuntu/Desktop/project_video.mp4")
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/VideoFileClip.py", line 81, in __init__
    fps_source=fps_source)
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 32, in __init__
    fps_source)
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 256, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

```
