### ISSUE TITLE
Hello, Can you fix that error please that I have?

### ISSUE THREAD

**Issue by Mohamed-Korium** [galenballew/SDC-Lane-and-Vehicle-Detection-Tracking#6]
Hello, Can you fix that error please that I have?

# Fit a per-column scaler
X_scaler = StandardScaler().fit(X)
# Apply the scaler to X
scaled_X = X_scaler.transform(X)

# Define the labels vector
y = np.hstack((np.ones(len(car_features)), np.zeros(len(notcar_features))))

ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-1a42ed1c49e0> in <module>()
     26 X = np.vstack((car_features, notcar_features)).astype(np.float64)
     27 # Fit a per-column scaler
---> 28 X_scaler = StandardScaler().fit(X)
     29 # Apply the scaler to X
     30 scaled_X = X_scaler.transform(X)

2 frames
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    592                              " a minimum of %d is required%s."
    593                              % (n_features, array.shape, ensure_min_features,
--> 594                                 context))
    595 
    596     if warn_on_dtype and dtype_orig is not None and array.dtype != dtype_orig:

ValueError: Found array with 0 feature(s) (shape=(2, 0)) while a minimum of 1 is required by StandardScaler.

**Comment by galenballew** [comment]
Hey Mohamed,

This error looks like it's to do with your data and not my code. I may be wrong. I hope that if you are using my code for your own education that you will debug the problem rather than ask me to do it for you. If you find an error in the code please feel free to submit a pull request! 

Thank you and good luck.
